name: hello docker
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: action/checkout@v3.3.0

      - name: run my own action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@wulfland'
          
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
